//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgriLogDBEntities : DbContext
    {
        public AgriLogDBEntities()
            : base("name=AgriLogDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit_Trail> Audit_Trail { get; set; }
        public virtual DbSet<Clocked> Clockeds { get; set; }
        public virtual DbSet<Day_Of_Week> Day_Of_Week { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Equipment_Type> Equipment_Type { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Farm_Type> Farm_Type { get; set; }
        public virtual DbSet<Farm_User> Farm_User { get; set; }
        public virtual DbSet<Farm_User_User_Position> Farm_User_User_Position { get; set; }
        public virtual DbSet<FarmHealth> FarmHealths { get; set; }
        public virtual DbSet<Fault_Log> Fault_Log { get; set; }
        public virtual DbSet<Fault_Staff> Fault_Staff { get; set; }
        public virtual DbSet<Fault_Type> Fault_Type { get; set; }
        public virtual DbSet<Importance> Importances { get; set; }
        public virtual DbSet<Infrastructure> Infrastructures { get; set; }
        public virtual DbSet<Infrastructure_Type> Infrastructure_Type { get; set; }
        public virtual DbSet<Insurance_Provider> Insurance_Provider { get; set; }
        public virtual DbSet<Login_Trail> Login_Trail { get; set; }
        public virtual DbSet<Maintenance_Log> Maintenance_Log { get; set; }
        public virtual DbSet<Maintenance_Staff> Maintenance_Staff { get; set; }
        public virtual DbSet<Maintenance_Type> Maintenance_Type { get; set; }
        public virtual DbSet<Password_Changelog> Password_Changelog { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Section_Type> Section_Type { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Notification_Log> Staff_Notification_Log { get; set; }
        public virtual DbSet<Staff_Skill> Staff_Skill { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Task_Skill> Task_Skill { get; set; }
        public virtual DbSet<Task_Task_Schedule> Task_Task_Schedule { get; set; }
        public virtual DbSet<Task_Type> Task_Type { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Notification_Log> User_Notification_Log { get; set; }
        public virtual DbSet<User_Position> User_Position { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Vehicle_Brand> Vehicle_Brand { get; set; }
        public virtual DbSet<Vehicle_Make> Vehicle_Make { get; set; }
        public virtual DbSet<Vehicle_Model> Vehicle_Model { get; set; }
        public virtual DbSet<Vehicle_Repair> Vehicle_Repair { get; set; }
        public virtual DbSet<Vehicle_Repair_Document> Vehicle_Repair_Document { get; set; }
        public virtual DbSet<Vehicle_Service> Vehicle_Service { get; set; }
        public virtual DbSet<Vehicle_Service_Document> Vehicle_Service_Document { get; set; }
        public virtual DbSet<Vehicle_Service_Provider> Vehicle_Service_Provider { get; set; }
        public virtual DbSet<Vehicle_Type> Vehicle_Type { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
