//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clocked
    {
        public string Clocked_ID { get; set; }
        public string Staff_ID { get; set; }
        public System.DateTime Clocked_In_Time { get; set; }
        public Nullable<System.DateTime> Clocked_Out_Time { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
