//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_User_User_Position
    {
        public string Farm_User_ID { get; set; }
        public int User_Type_ID { get; set; }
        public int Farm_ID { get; set; }
        public int farm_User_User_Position_ID { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual Farm_User Farm_User { get; set; }
        public virtual User_Position User_Position { get; set; }
    }
}
