//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmHealth
    {
        public int Health_ID { get; set; }
        public int Farm_ID { get; set; }
        public System.DateTime Health_Date_Calculated { get; set; }
        public Nullable<int> Fault_Score { get; set; }
        public Nullable<int> Task_Score { get; set; }
        public Nullable<int> Vehicle_Score { get; set; }
        public Nullable<int> Maintenance_Score { get; set; }
        public Nullable<int> Overall_Score { get; set; }
    
        public virtual Farm Farm { get; set; }
    }
}
