//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm()
        {
            this.Audit_Trail = new HashSet<Audit_Trail>();
            this.Equipments = new HashSet<Equipment>();
            this.Equipment_Type = new HashSet<Equipment_Type>();
            this.Farm_User_User_Position = new HashSet<Farm_User_User_Position>();
            this.FarmHealths = new HashSet<FarmHealth>();
            this.Fault_Type = new HashSet<Fault_Type>();
            this.Sections = new HashSet<Section>();
            this.Section_Type = new HashSet<Section_Type>();
            this.Skills = new HashSet<Skill>();
            this.Staffs = new HashSet<Staff>();
            this.Vehicles = new HashSet<Vehicle>();
            this.Vehicle_Service_Provider = new HashSet<Vehicle_Service_Provider>();
            this.Vehicle_Type = new HashSet<Vehicle_Type>();
        }
    
        public int Farm_ID { get; set; }
        public int Farm_Type_ID { get; set; }
        public int Province_ID { get; set; }
        public Nullable<int> IP_ID { get; set; }
        public string Farm_Name { get; set; }
        public string Farm_Size { get; set; }
        public string Farm_Address { get; set; }
        public string Farm_Email { get; set; }
        public string Farm_ContactNumber { get; set; }
        public int Farm_Avg_Health_Score { get; set; }
        public bool Is_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Trail> Audit_Trail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Type> Equipment_Type { get; set; }
        public virtual Farm_Type Farm_Type { get; set; }
        public virtual Insurance_Provider Insurance_Provider { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_User_User_Position> Farm_User_User_Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmHealth> FarmHealths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fault_Type> Fault_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section_Type> Section_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Service_Provider> Vehicle_Service_Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Type> Vehicle_Type { get; set; }
    }
}
