//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm_User()
        {
            this.Farm_User_User_Position = new HashSet<Farm_User_User_Position>();
        }
    
        public string Farm_User_ID { get; set; }
        public int User_ID { get; set; }
        public string Farm_User_Name { get; set; }
        public string Farm_User_Surname { get; set; }
        public System.DateTime Farm_User_DOB { get; set; }
        public string Farm_User_Address { get; set; }
        public string Farm_User_Phone_Number { get; set; }
        public string Farm_User_Image { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_User_User_Position> Farm_User_User_Position { get; set; }
    }
}
