//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault_Staff
    {
        public int Fault_ID { get; set; }
        public string Staff_ID { get; set; }
        public int FaultStaff_Id { get; set; }
    
        public virtual Fault_Log Fault_Log { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
