//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurance_Provider()
        {
            this.Farms = new HashSet<Farm>();
        }
    
        public int IP_ID { get; set; }
        public int User_ID { get; set; }
        public string IP_Name { get; set; }
        public string IP_Reg_Number { get; set; }
        public string IP_VAT_Number { get; set; }
        public string IP_Phone_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm> Farms { get; set; }
        public virtual User User { get; set; }
    }
}
