//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Trail
    {
        public int Trail_ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Login_DateTime { get; set; }
        public Nullable<System.DateTime> Logout_DateTime { get; set; }
        public string User_IP_Address { get; set; }
        public string Is_Active { get; set; }
    
        public virtual User User { get; set; }
    }
}
