//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintenance_Log()
        {
            this.Maintenance_Staff = new HashSet<Maintenance_Staff>();
        }
    
        public int Maintenance_ID { get; set; }
        public int MT_ID { get; set; }
        public int Status_ID { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public Nullable<int> Infrastructure_ID { get; set; }
        public int Importance_ID { get; set; }
        public string Maintenance_Description { get; set; }
        public System.DateTime Maintenance_Start_Date { get; set; }
        public Nullable<System.DateTime> Maintenance_End_Date { get; set; }
        public string Maintenance_Image { get; set; }
        public Nullable<int> Section_ID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Importance Importance { get; set; }
        public virtual Infrastructure Infrastructure { get; set; }
        public virtual Maintenance_Type Maintenance_Type { get; set; }
        public virtual Section Section { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Staff> Maintenance_Staff { get; set; }
    }
}
