//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Skill
    {
        public string Staff_ID { get; set; }
        public int Skill_ID { get; set; }
        public int StaffSkill_ID { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
