//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Task_Skill = new HashSet<Task_Skill>();
            this.Task_Task_Schedule = new HashSet<Task_Task_Schedule>();
        }
    
        public int Task_ID { get; set; }
        public int Task_Type_ID { get; set; }
        public int Importance_ID { get; set; }
        public int Section_ID { get; set; }
        public Nullable<int> Infrastructure_ID { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public string Task_Description { get; set; }
        public string Task_Duration { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Importance Importance { get; set; }
        public virtual Infrastructure Infrastructure { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Skill> Task_Skill { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual Task Task2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Task_Schedule> Task_Task_Schedule { get; set; }
        public virtual Task_Type Task_Type { get; set; }
    }
}
