//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Notification_Log
    {
        public int UNL_ID { get; set; }
        public int User_ID { get; set; }
        public string UNL_Message { get; set; }
        public System.DateTime Date_Time_Sent { get; set; }
    
        public virtual User User { get; set; }
    }
}
