//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Vehicle_Repair = new HashSet<Vehicle_Repair>();
        }
    
        public int Vehicle_ID { get; set; }
        public Nullable<int> Vehicle_Type_ID { get; set; }
        public Nullable<int> Vehicle_Brand_ID { get; set; }
        public Nullable<int> Infrastructure_ID { get; set; }
        public Nullable<int> Section_ID { get; set; }
        public string Vehicle_Year { get; set; }
        public string Vehicle_Colour { get; set; }
        public string Vehicle_Mileage_Date_Of_Purchase { get; set; }
        public string Vehicle_Mileage_Current { get; set; }
        public string Vehicle_Service_Intervals { get; set; }
        public string Vehicle_Last_Service_Mileage { get; set; }
        public string Vehicle_Registration_Number { get; set; }
        public Nullable<System.DateTime> Vehicle_Date_Of_Purchase { get; set; }
        public string Vehicle_Purchase_Price { get; set; }
        public string Is_Active { get; set; }
        public Nullable<int> Farm_ID { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual Infrastructure Infrastructure { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Repair> Vehicle_Repair { get; set; }
        public virtual Vehicle_Brand Vehicle_Brand { get; set; }
        public virtual Vehicle_Type Vehicle_Type { get; set; }
    }
}
