//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriLogBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Service
    {
        public int Vehicle_Service_ID { get; set; }
        public int Provider_ID { get; set; }
        public string Vehicle_Service_Document { get; set; }
        public int Vehicle_ID { get; set; }
        public int Status_ID { get; set; }
        public string Vehicle_Service_Mileage { get; set; }
        public System.DateTime Vehicle_Service_Start_Date { get; set; }
        public System.DateTime Vehicle_Service_End_Date { get; set; }
        public string Vehicle_Service_Description { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Vehicle_Service_Provider Vehicle_Service_Provider { get; set; }
    }
}
